board/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('board.views',
    (r"^profile/$", "profile"),
    (r"^(\d{1,2})/add_thread/$", "add_thread"),
    (r"^unit/(\d{1,2})/(\d+)/$", "thread"),
    
    (r"^unit/(\d{1,2})/$", "unit"),
    (r"", "main"),
)

proj1/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^advert/$', 'main.views.advert'),
    (r'^stat/$', 'main.views.stat'),
    (r'^board/', include('board.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'accounts/', include('registration.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT}),
     (r'^$', 'main.views.index'),                 
)
     

board/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.db.models.signals import post_save


class Board(models.Model):
    title = models.CharField(max_length=50)
    def __unicode__(self):
        return unicode(self.title)

class Thread(models.Model):
    title = models.CharField(max_length=50)
    board = models.ForeignKey(Board)
    creator = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ["-changed"]
        get_latest_by = 'changed'
        
    def __unicode__(self):
        return unicode(self.title)
    


class Post(models.Model):
    title = models.CharField(max_length=50, blank=True)
    body = models.TextField(max_length=5000, blank=False)
    thread = models.ForeignKey(Thread)
    creator = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        get_latest_by = 'created'
    
    def __unicode__(self):
        return unicode(self.title)
    
class UserProfile(models.Model):
    city = models.CharField(max_length=30, verbose_name=u'Город', blank=True)
    pet = models.CharField(max_length=30, verbose_name=u'Питомец', blank=True)
    nick = models.CharField(max_length=50, verbose_name=u'Имя', unique=True, null=True)
    avatar = models.ImageField(upload_to='images/', null=True, blank=True)
    user = models.ForeignKey(User)
    
    def __unicode__(self):
        return unicode(self.user)
    
        
    def user_email(self):
        return self.user.email

    
#Admin section

class BoardAdmin(admin.ModelAdmin):
    list_display = ['title']
class ThreadAdmin(admin.ModelAdmin):
    list_display = ['title', 'creator', 'created']
class PostAdmin(admin.ModelAdmin):
    list_display = ['title', 'thread', 'creator']
class ProfileAdmin(admin.ModelAdmin):
    list_display = ['user', 'city', 'user_email']

def create_profile(sender, **kwargs):
    created = kwargs['created']
    if created:
        UserProfile.objects.create(user=kwargs['instance'])
        
post_save.connect(create_profile, sender=User)

main/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
import os.path


class Advert(models.Model):
    TYPE_CHOICES = (
        (0, 'потерян'),
        (1, 'найден'),
    )
    advtype = models.IntegerField(max_length=1, choices = TYPE_CHOICES)
    title = models.CharField(max_length=30)
    body = models.TextField(max_length=250)
    longitude = models.FloatField()
    latitude = models.FloatField()
    city = models.CharField(max_length=80, blank=True)
    country = models.CharField(max_length=80, blank=True)
    photo = models.ImageField(upload_to='images/advert/', blank=True, null=True)
    creator = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        get_latest_by = 'created'
        
    def __unicode__(self):
        return unicode(self.title)
        
    def filename(self):
        return os.path.basename(self.photo.name)
    
    
        
  
  
 
    
class AdvertAdmin(admin.ModelAdmin):
    list_display = ['title', 'creator']

board/forms.py
# -*- coding: utf-8 -*-
from django import forms
from board.models import UserProfile, Thread, Post
#from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    body = forms.CharField(label="",
            widget = forms.Textarea(attrs={'cols':70, 'rows':5,}))
    class Meta:
        model = Post
        hi = forms.HiddenInput
        widgets = {'title':hi, 'thread':hi, 'creator':hi}

class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        widgets = {'creator': forms.HiddenInput,}

class ProfileForm(forms.ModelForm):
    city = forms.CharField(required=False, label = 'Город')
    class Meta:
        model = UserProfile
        exclude = ('user',)
    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']
        if avatar:
            try:
                if len(avatar) > (1024 * 3072):
                    raise forms.ValidationError(u'Размер файла не должен превышать 3 Mb')
            except AttributeError:
                pass
            return avatar

main/forms.py
# -*- coding: utf-8 -*-
from django import forms
from main.models import Advert

class AdvertForm(forms.ModelForm):
    title = forms.CharField(label='Заголовок', max_length=30)
    city = forms.CharField(label='Город',)
    photo = forms.ImageField(required=False, label='Фотография',)
    body = forms.CharField(label='Текст 0 символов из 250', max_length=250,
            widget = forms.Textarea(attrs={'cols':15, 'rows':4}))
    advtype = forms.ChoiceField(label="",choices=Advert.TYPE_CHOICES,
                                widget = forms.RadioSelect())
    
    class Meta:
        model = Advert
        widgets = {'creator': forms.HiddenInput,
                   'longitude':forms.HiddenInput,
                   'latitude':forms.HiddenInput,
                   'country':forms.HiddenInput}
                   
    def clean_photo(self):
        photo = self.cleaned_data['photo']
        try:
            if photo:
                if len(photo) > (1024 * 3072):
                    raise forms.ValidationError(u'Размер файла не должен превышать 3 Mb')
        except AttributeError:
            pass
        return photo
        
    def clean_body(self):
        body = self.cleaned_data['body']
        try:
            if body:
                if len(body) > 250:
                    raise forms.ValidationError(u'Размер текста не должен превышать 250 символов')
        except AttributeError:
            pass
        return body

board/views.py
# -*- coding: utf-8 -*-
from board.models import *
from main.models import Advert
from board.forms import *
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from PIL import Image
import os
from proj1.settings import MEDIA_ROOT, MEDIA_URL
from os.path import join as pjoin

@login_required
def add_thread(request, unitid):
    board = Board.objects.get(pk=unitid)
    form = ThreadForm(initial={'board':board, 'creator':request.user})
    
    if request.method == 'POST':
        form = ThreadForm(request.POST)
        if form.is_valid:
            try:
                form.save()
                latest = unicode(Thread.objects.latest('pk').id)
                return HttpResponseRedirect('/board/unit/'+unitid+'/'+latest+'/')
            except ValueError:
                pass
    return render_to_response('board/add_thread.html', add_csrf(request,
                                                        unitid=unitid,
                                                        form=form,
                                                        ))
                  
                                      
def main(request):
    boards = Board.objects.all()
    return render_to_response('board/main.html', {'boards': boards, 'user':request.user
                                                  })
    
    
def unit(request, unitid):
    threads = Thread.objects.filter(board=unitid)
    records = paging(request,threads, 15)
    return render_to_response('board/unit.html', {'user':request.user,
                                                  'unitid':unitid,
                                                  'records':records})


def thread(request, unitid, threadid):
    posts = Post.objects.all().filter(thread=threadid).order_by('created')
    thread = Thread.objects.get(pk=threadid)
    title = 'Re: ' + thread.title
    page1=''
    if not posts:
        title = thread.title
    records = paging(request, posts, 5)
    
    form = PostForm(initial={'title':title, 'thread':threadid, 'creator':request.user})
    if request.method == 'POST':
        form = PostForm(request.POST)
        page = unicode(records.end_index())
        if form.is_valid:
            try:
                form.save()
                thread.save()
                return HttpResponseRedirect('/board/unit/'+unitid+'/'+threadid+'/?page='+page)
            except ValueError:
                pass
            
            
    return render_to_response('board/thread.html', add_csrf(request,
                                                    records=records,
                                                    unitid=unitid,
                                                    threadid=threadid,
                                                    form=form,
                                                    thread=thread,
                                                    profile=profile))
                                                    
                                                    
@login_required
def profile(request, **kwargs):
    user = UserProfile.objects.get(user=request.user)
    adverts = Advert.objects.filter(creator=request.user).order_by('-created')
    form = ProfileForm(instance=user)
    oldavatar = user.avatar.name
        
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid:
            try:
                form.save()
                iname = user.avatar.name
                if iname:
                    im, temp, format = image_resize(iname, 50)
                
                if user.avatar.name != oldavatar:
                    im.save(temp, format)
                    if oldavatar:
                        temp = pjoin(MEDIA_ROOT, oldavatar)
                        os.remove(temp)
                return HttpResponseRedirect('board')
            except ValueError:
                pass
                
    return render_to_response('board/profile.html', add_csrf(request,
                                                    form=form,
                                                    adverts=adverts,
                                                    ))
                                                     
                                                     
def paging(request, data, records_onpage):
    paginator = Paginator(data, records_onpage)
    page = request.GET.get('page')
    try:
        records = paginator.page(page)
    except PageNotAnInteger:
        records = paginator.page(1)
    except EmptyPage:
        records = paginator.page(paginator.num_pages)
    return records


def image_resize(iname, size):
    temp = pjoin(MEDIA_ROOT, iname)
    im = Image.open(temp)
    format = im.format
    if im.mode not in ('L', 'RGBA'):
        im = im.convert('RGBA')
    im.thumbnail((size,size), Image.ANTIALIAS)
    return im, temp, format
    
def add_csrf(request, **kwargs):
    d = dict(user=request.user, **kwargs)
    d.update(csrf(request))
    return d

main/views.py
# -*- coding: utf-8 -*-
from main.models import Advert
from main.forms import AdvertForm
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, render_to_response
from board.views import add_csrf
from proj1.settings import MEDIA_ROOT
from board.views import image_resize, paging
from django.utils import simplejson 
from os.path import join as pjoin
import datetime
#from PIL import Image
#import random
import os




def index(request):
    period = request.GET.get('period')  
    atype = request.GET.get('atype')
    if not period:
        period = 7
    delta = datetime.datetime.now() - datetime.timedelta(days=int(period))
    if not atype or int(atype) > 1:
        advs = Advert.objects.filter(created__gte=delta).order_by('-created')
    else:
        advs = Advert.objects.filter(created__gte=delta).filter(advtype=atype).order_by('-created')
    adverts = [ {'adv_id':adv.id, 'x':adv.longitude, 'y':adv.latitude,
                                'advtype':adv.advtype, 'img':adv.filename(),
                                'title':adv.title, 'body':adv.body,
                                'city':adv.city, 'country':adv.country,
                                'stamp':adv.created.strftime('%d-%m-%Y'),
                                } for adv in advs ]
                                
    return render(request, 'main/index.html', {
        'advjson': simplejson.dumps(adverts),
        'user': request.user,
        })

@login_required
def advert(request):
    form = AdvertForm(initial={'creator':request.user,})
    if request.method == 'POST':
        form = AdvertForm(request.POST, request.FILES)
        if form.is_valid:
            try:
                if request.FILES:
                    photoName = request.FILES['photo'].name
                    iname = 'images/advert/' + photoName
                    test = pjoin(MEDIA_ROOT, iname)
                    if os.path.exists(test):
                        razb = photoName.split('.')
                        n = unicode(os.urandom(16).encode('hex'))
                        request.FILES['photo'].name = razb[0] + n + '.' + razb[-1]
                        photoName = request.FILES['photo'].name
                        iname = 'images/advert/' + photoName
                form.save()
                
                if request.FILES:
                    im, temp, format = image_resize(iname, 600)
                    im.save(temp, format)
                
                    im, temp, format = image_resize(iname, 100)
                    iname = 'images/advert/thumb/' + photoName
                    temp = pjoin(MEDIA_ROOT, iname)
                    im.save(temp, format)
                
                return HttpResponseRedirect('/stat/')
            except ValueError:
                pass
    
    
    return render_to_response('main/advert.html', add_csrf(request,
                                                   form=form,
                                                   ))
                                                   
def stat(request):
    period = request.GET.get('period')  
    town = request.GET.get('town')
    params = request.GET.copy()
    path = params.urlencode()
    if not period:
        period = 7
    if not town:
        town = ''
    delta = datetime.datetime.now() - datetime.timedelta(days=int(period))
    adverts = Advert.objects.filter(created__gte=delta).filter(city__icontains=town).order_by('-created')
    records = paging(request, adverts, 40)
    return render_to_response('main/stat.html', {'user':request.user,
                                                   'records':records,
                                                   'period':period,
                                                   'town':town,
                                                   'path':path,
                                                   })
                                                   
                                                   
                                                   


    

proj1/templates/board/add_thread.html
{% extends "main/mbase.html" %}

{% block header %} - Добавление темы {% endblock %}

{%block title%} Создание новой темы {% endblock %}

{% block main %}
<div id="form">
<form method="POST" action="" type="text">
{{ form.as_ul }}
<br><br>
<li>
<input type="submit" class="bigsubmit" value="Добавить">{% csrf_token %}
</li>
</form>
</div>
{% endblock %}

proj1/templates/board/main.html
{% extends "main/mbase.html" %}
{% block header %} - Форум {% endblock %}
{% block title %} Форум {% endblock %}
{% block main %}
<div id="board" >
{% for board in boards %}
<li><a href="/board/unit/{{board.id}}/">{{ board.title }}</a>&nbsp;&nbsp;<span id="scrib">(тем:{{board.thread_set.count}})</span></li>
 <span id="scrib">последняя запись в теме:
"{{board.thread_set.latest.title}}",  автор:
{% if board.thread_set.latest.post_set.latest %}
    {{board.thread_set.latest.post_set.latest.creator.get_profile.nick}},
    {{board.thread_set.latest.post_set.latest.created}}
{% else %}
    {{board.thread_set.latest.creator.get_profile.nick}},
    {{board.thread_set.latest.created}},
  
{% endif %}  

</span>
<br> <br> 

{% endfor %}
</div>
{% endblock %}


начинаю

proj1/templates/board/profile.html
{% extends "main/mbase.html" %}

{% block header %} - Профиль {% endblock %}

{%block main %}

 {% if error_mesage %}
   {{ error_message }}
 {% endif %}
 {%if user.get_profile.avatar %}
 <img src="{{user.get_profile.avatar.url}}">
 {% endif %}
 <br><br><br>
 <div id="form">
 <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
  {{ form.as_ul }}
 <br>
 <li> 
 <input type="submit" class="bigsubmit"  value="Сохранить" />
 </li>
 </form>
 </div>
 
 <div id=profileadverts>
  <h2> Мои объявления: </h2>
  {% for advert in adverts %}
  <table>
  <tr> 
     <td>{{ advert }}. <td>
     <td> &nbsp;&nbsp;Создано:{{advert.created}}
 </tr>  
  <table>
  {% endfor%}
 </div>
    
{% endblock %}

proj1/templates/board/thread.html
{% extends "main/mbase.html" %}

{% block header %} - {{ thread.title }} {% endblock %}

{% block title %} {{ thread.title }} {% endblock %}

{% block main %}

<div id="board">
<div id="thread">
{% for post in records %}
<div id="comm">
  {#  <div id="last">{{ post.title }} </div> #}
   <p> {{ post.body }} </p>
    {%if post.creator.get_profile.avatar %}
     <img src="{{post.creator.get_profile.avatar.url}}">
    {% endif %}
     <span id="last">- Написал &nbsp {{post.creator.get_profile.nick }} &nbsp {{post.created|date:"d F Y в G:i"}}</span>
    <br><br>
</div>
<br>
{% endfor %}
<br>
{% if user.is_authenticated %}
    <div id="formpost">
    <form method="POST" action="" type="text"> {% csrf_token %}
    <br>
    {{ form.as_ul }}
    <input type="submit" class="bigsubmit"   id="postsubmit" value="Отправить">
    </div>
    </body>
    </form>
{% endif %}
</div>
{% endblock %}

{% block pagination %}
    
    {% if records.has_previous %}
        <a href="page={{ records.previous_page_number }}">назад</a>
    {% endif %}
    
    {% for record in records.paginator.page_range %}
        {%if record = records.number %}
        <a href="?page={{ record }}"><span>{{ record }}</span></a>&nbsp; 
        {% else %}
         <a href="?page={{ record }}">{{ record }}</a>&nbsp; 
        {% endif%}
    {% endfor%}

    {% if records.has_next %}
        <a href="?page={{ records.next_page_number }}">вперед</a>
    {% endif %}
    
</div>

{% endblock %}

proj1/templates/board/unit.html
{% extends "main/mbase.html" %}

{% block header %} - {{ records.0.board }} {% endblock %}

{% block title %} {{records.0.board }} {% endblock %}

    

{% block main %}
<div id="board">
{% if user.is_authenticated %}
        <li ><a id="add_thread" href="/board/{{unitid}}/add_thread/">Добавить тему</a></li>
         <br>
{% endif%} 

    {% for thread in records %}
      <li>  <a href="/board/unit/{{unitid}}/{{thread.id}}/">{{ thread.title }}</a> 
       <span> &nbsp;&nbsp;(комментариев:{{thread.post_set.count}})</span></li>
<span id="scrib">создан:&nbsp;{{thread.creator.get_profile.nick}}&nbsp;{{thread.created}},&nbsp;
изменен:&nbsp;{{thread.post_set.latest.creator.get_profile.nick}} {{thread.changed}}
</span>
        <br><br>
    {% endfor %}
<br>

{% endblock %}



{% block pagination %}
    
    {% if records.has_previous %}
        <a href="?page={{ records.previous_page_number }}">назад</a>
    {% endif %}
    
    {% for record in records.paginator.page_range %}
        {%if record = records.number %}
        <a href="?page={{ record }}"><span>{{ record }}</span></a>&nbsp; 
        {% else %}
         <a href="?page={{ record }}">{{ record }}</a>&nbsp; 
        {% endif%}
    {% endfor%}

    {% if records.has_next %}
        <a href="?page={{ records.next_page_number }}">вперед</a>
    {% endif %}
    
</div>

{% endblock %}